### ISSUE TITLE
Pull and push from the current branch.

### ISSUE THREAD

**Issue by franciscoj** [anvil-src/anvil-core#19]

**Comment by aviscasillas** [comment]
Hi @franciscoj! 
I'm just now working on do pull&push on current_branch for `Gem::BumpTask`. 
Do you mean this here?

Do you want me to open the PR?

**Comment by franciscoj** [comment]
Yes please!!

**Comment by aviscasillas** [comment]
@franciscoj done!

**Comment by franciscoj** [comment]
Closed as @aviscasillas solved it here https://github.com/anvil-src/anvil-core/pull/40.

Thanks again!
